### ISSUE TITLE
About iSeg2017 datasets

### ISSUE THREAD

**Issue by wenwenyu** [marianocabezas/challenges2017#2]
Hi
When I download iSeg2017 datasets from [there](http://iseg2017.web.unc.edu/download/) .It request create a team firstly from [there](https://form.jotform.us/form/70697708695172) ,but this link is not work.Do you have the same problem? If you not, can you provide iSeg2017 datasets due to I can't download.
Thinks!

**Comment by marianocabezas** [comment]
I downloaded the dataset when they opened the challenge last year, but since I didn't work on it, I deleted the data from my computer. Try asking the organizers for the data:

http://iseg2017.web.unc.edu/organizers/

Maybe they can help you! :)

**Comment by wenwenyu** [comment]
Thinks!

**Comment by lichen14** [comment]
@wenwenyu hi, did u get the iseg dataset? thanks for sharing!
